version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      MSSQL_SA_PASSWORD: 'YourStrong@Passw0rd'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    volumes:
      - ./mssql-data:/var/opt/mssql
